use-grammars = { only = [
  "bash",
  "diff",
  "dockerfile",
  "git-commit",
  "git-config",
  "gitignore",
  "git-rebase",
  "html",
  "ini",
  "json",
  "markdown",
  "markdown_inline",
  "log",
  "lua",
  "python",
  "rst",
  "toml",
  "yaml",
] }

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.harper-ls.config.harper-ls.linters]
long_sentences = false
wrong_quotes = true
linking_verbs = true


[language-server.ltex-ls.config]
# Disable `MORFOLOGIK`-rules for English, and use instead Harper as spell checker.
ltex.disabledRules = { "en-US" = [
  "MORFOLOGIK_RULE_EN_US",
], "en-GB" = [
  "MORFOLOGIK_RULE_EN_GB",
] }


[language-server.lua-language-server.config.Lua.diagnostics]
globals = ["vim"]

[language-server.lua-language-server.config.Lua.telemetry]
enable = false

[language-server.lua-language-server.config.Lua.workspace]
checkThirdParty = false

[language-server.pyright.config.python]
analysis = { typeCheckingMode = "basic" }
disableOrganizeImports = false

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.vale-ls]
command = "vale-ls"

[language-server.vscode-json-language-server.config]
provideFormatter = false
json = { format = { enable = false }, validate = { enable = true } }

[language-server.yaml-language-server.config.yaml]
format = { enable = false }
keyOrdering = false
validate = { enable = true }
schemas = { "https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json" = ".gitlab-ci.{yml,yaml}", "https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json" = "**/lazygit/config.yml" }


[[language]]
name = "bash"
file-types = [
  "bash",
  "sh",
  "tmux",
  "zsh",
  "zshenv",
  "zshrc",
  { glob = "tmux.conf" },
  { glob = ".bash_history" },
  { glob = ".bash_logout" },
  { glob = ".bash_profile" },
  { glob = ".bashrc" },
  { glob = ".profile" },
  { glob = ".zshenv" },
]
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'shfmt', args = ["-i", "2"] }
auto-format = true

[[language]]
name = "ini"
file-types = [
  "ini",
  { glob = ".coveragerc" },
  { glob = ".editorconfig" },
  { glob = ".npmrc" },
  { glob = "npmrc" },
]

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }
language-servers = ["vscode-html-language-server", "vale-ls", "harper-ls"]

[[language]]
name = "json"
formatter = { command = 'deno', args = ["fmt", "-", "--ext", "json"] }

[[language]]
name = "lua"
language-servers = ["lua-language-server", "vale-ls", "harper-ls"]
formatter = { command = "stylua", args = ["-"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "harper-ls", "ltex-ls", "vale-ls"]
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff", "harper-ls", "vale-ls"]
formatter = { command = "ruff", args = ["format", "--line-length", "88", "-"] }
auto-format = true

[[language]]
name = "toml"
language-servers = ["taplo", "harper-ls"]
formatter = { command = "taplo", args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "yaml"
language-servers = ["yaml-language-server", "harpe-ls"]
formatter = { command = 'prettier', args = ["--parser", "yaml"] }
auto-format = true
